apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-alert-rules
  namespace: monitoring
spec:
  groups:
  - name: flask-app-rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{image!="",name=~"^flask-.*"}[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage for Flask app"
        description: "The Flask app is using over 50% CPU for more than 5 minutes."
